{% set name = "opentelemetry-instrumentation-httpx" %}
{% set version = "0.27b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-httpx-{{ version }}.tar.gz
  sha256: 5cbf99ecc7941dfc3e6f3d15393ea7bd41a3ed4715fc1f2d10c39f2610c81cb5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.27b0
    - opentelemetry-semantic-conventions ==0.27b0
    - python >=3.6
    - wrapt <2.0.0,>=1.0.0
    # - respx ~=0.17.0
    # - opentelemetry-test ==0.24b0
    # - opentelemetry-sdk ~=1.3
    # - httpx <0.19.0,>=0.18.0
    # - respx ~=0.17.0
    # - opentelemetry-test ==0.25b0
    # - opentelemetry-sdk ~=1.3
    # - httpx <0.19.0,>=0.18.0
    # - respx ~=0.17.0
    # - opentelemetry-test ==0.25b1
    # - opentelemetry-sdk ~=1.3
    # - httpx <0.19.0,>=0.18.0
    # - respx ~=0.17.0
    # - opentelemetry-test ==0.25b2
    # - opentelemetry-sdk ~=1.3
    # - httpx <0.19.0,>=0.18.0
    # - respx ~=0.17.0
    # - opentelemetry-test-utils ==0.26b1
    # - opentelemetry-sdk ~=1.3
    # - httpx <0.19.0,>=0.18.0
    # - respx ~=0.17.0
    # - opentelemetry-test-utils ==0.27b0
    # - opentelemetry-sdk ~=1.3
    # - httpx <0.19.0,>=0.18.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-httpx
  summary: OpenTelemetry HTTPX Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
