{% set name = "opentelemetry-instrumentation-httpx" %}
{% set version = "0.25b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-httpx-{{ version }}.tar.gz
  sha256: f377964e8c0b599a6aee779c7a6d16c3bf44cbc693268f46d79019cf712e02d2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.25b1
    - opentelemetry-semantic-conventions ==0.25b1
    - python >=3.6
    - wrapt <2.0.0,>=1.0.0
    # - respx ~=0.17.0
    # - opentelemetry-test ==0.24b0
    # - opentelemetry-sdk ~=1.3
    # - httpx <0.19.0,>=0.18.0
    # - respx ~=0.17.0
    # - opentelemetry-test ==0.25b0
    # - opentelemetry-sdk ~=1.3
    # - httpx <0.19.0,>=0.18.0
    # - respx ~=0.17.0
    # - opentelemetry-test ==0.25b1
    # - opentelemetry-sdk ~=1.3
    # - httpx <0.19.0,>=0.18.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-httpx
  summary: OpenTelemetry HTTPX Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
